### ISSUE TITLE
Linode mentions of pending upgrades & need to put a machine in a queue - do we want these? what are these?

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/grittyOps#18]

**Comment by bibliotechy** [comment]
When Linode changes their pricing model, which happens 1 or two times per year, you often get more ram or Disk or CPU for the same price. They have an automated process for migrating you to the improved sized box, but it can take a couple of hours.

**Comment by cmharlow** [comment]
So @bibliotechy we should make sure our machines are in that queue for automated migration?

**Comment by cmharlow** [comment]
ping @bibliotechy

**Comment by cmharlow** [comment]
helllooooooo @bibliotechy

**Comment by bibliotechy** [comment]
@cmharlow Sorry. The queue for migration could mean several hours of dowtime per box. I'm sure we coudl safely do this for any QA machine on a weekend we'd be fine. I'm a little more hesitant with prod machines, for obvious reasons.

**Comment by cmharlow** [comment]
so we should make sure all qa, stage, dev machines are in queue; all prod machines need to be planned and should wait for migration to distributed architecture. just making that decision and moving this forward.
