### ISSUE TITLE
what is up with the Linode custom TUL AMI disk usage?

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/grittyOps#20]
Spinning up a 8 GB etc. box with the AMI leads to a VM that cannot run the ansible_server_bootstrap playbook bc it errors out on lack of file space running yum * update. Would like to walk through this with @bibliotechy to try to debug 

Also about that AMI - does it need any updates?

**Comment by bibliotechy** [comment]
The AMI by default is only a 2GB volume, so when building a new box with the AMI via the GUI, no matter how large of a box you pick, it still spins up with only a 2GB volume. After it is created, I have to manually go into the UI and alter the volume size to use the available space. So, maybe you are hitting the same issue? Is terraform explicitly setting the volume size?

It was last updated 2018-11-09, so it certainly needs an update with your keys at very least.

**Comment by cmharlow** [comment]
known issue (per above), to repair:
- create in GUI with appropriate AMI;
- power off in GUI;
- Advanced Options > Size then Expand Image (to all disk space)

Alternate option: if we go with meta-terraform for consul or whatever backend, just use local state file and tell nobody else to touch them. This may give us terraform option for expanding disk to full AMI automatically.
