### ISSUE TITLE
make Consul more robust

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/grittyOps#42]
- [x] have fully functioning consul deployment script (ansible playbook or docker-compose)
- [x] create multiple ACLs
- [x] link more granular ACLs to new access tokens
- [x] use more granular access tokens in clients, primarily, inter-node communication, UI / API access, and Atlantis / local terraform.
- [ ] create small cluster in another datacenter, communicating via WAN
- [x] start using consul clients on existing infra services (atlantis, traefik, airflow)

**Comment by cmharlow** [comment]
- [ ] create multiple ACLs
- [ ] link more granular ACLs to new access tokens
- [ ] use more granular access tokens in clients, primarily, inter-node communication, UI / API access, and Atlantis / local terraform.
- [ ] create small cluster in another datacenter, communicating via WAN
- [ ] load balance UI via traefik (?? will open API to more access? certs limitations?)
- [ ] start using consul clients on existing infra services (atlantis, traefik, airflow)

**Comment by bibliotechy** [comment]
As I'm trying to spin up consul docker inside a bootstrapped vm, I have questions I'm working through
-  How to get the appropriate docker-compose.yml, consul config files, etc, in place when they will differ by machine? Use Terraform exec? Use Ansible role?
-  Do we run docker compose as a systemd service? Is there another way to make sure it is running on boot? If so, same question as above about systemd files? 
  - This [example](https://gist.github.com/Luzifer/7c54c8b0b61da450d10258f0abd3c917) looks interesting.
- Looks like firewalld and docker-compose don't always play well together - I'm seeing the issues described in [this issue](https://github.com/moby/moby/issues/16137)

**Comment by cmharlow** [comment]
@bibliotechy are you still working on this?

**Comment by cmharlow** [comment]
@bibliotechy re-assigning since I need to fix this to fix other infra things.
