### ISSUE TITLE
Post-mortems(team standards)

### ISSUE THREAD

**Issue by sensei100** [tulibraries/grittyOps#53]
https://github.com/NYPL/engineering-general/blob/master/standards/postmortems.md

They have some great resources for this, including links to learn more about post-mortems and a sample template.

**Comment by cmharlow** [comment]
Discussion:
- NYPL has a good structure for what they review & document for post-mortems
- Reading links they had about more on post-mortems
  - maybe we should do them more often than we do
- Related to blame-free culture; 

General approval
