### ISSUE TITLE
can we make dummy vault vaules for local playbook testing, or will it fail?

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/grittyOps#6]

**Comment by bibliotechy** [comment]
We do do some of this in places like, https://github.com/tulibraries/tul_cob_playbook/blob/nginx-changes/group_vars/all.yml#L36  where `honeybadger_api_key` is vaulted for some inventories that require it https://github.com/tulibraries/tul_cob_playbook/blob/nginx-changes/inventory/beta/group_vars/all.yml#L28 but can not exit without effecting the system.

**Comment by cmharlow** [comment]
Confirmed, thanks @bibliotechy
