### ISSUE TITLE
Generate tech-team focused master list of links for docs & resources

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/grittyOps#66]

**Comment by cmharlow** [comment]
See https://github.com/NYPL/engineering-general/blob/master/other/README.md

**Comment by cmharlow** [comment]
Approval to get this started

**Comment by cmharlow** [comment]
@cmharlow + @ebtoner to re-prioritize this

**Comment by ebtoner** [comment]
I've been working on this in recent weeks. Regarding Confluence documentation that already exists, I'm torn whether we should just to Confluence or move that documentation over to GrittyOps. Also, I'm not sure how @amecynth and @dlacy feel about linking to our TUL Confluence page on a public repo -- thoughts?

**Comment by amecynth** [comment]
Sorry, I'm not too familiar with Github, where is the actual documentation stored?

Regarding linking to Confluence: If you link to a Confluence page that is not viewable to the public, I think Confluence will ask for a login, so that should be fine.

**Comment by amecynth** [comment]
This looks good. I would focus on documentation in Github for the code that is in Gitbub. But it looks like you're doing this already.

**Comment by cmharlow** [comment]
Need to remove dev portfolios gantt chart; waiting for @bibliotechy to respond with what docs will exist for dev portfolios management + resource allocation; and need to update with all deprecated Confluence spaces being move to here.
